---
- name: Add the hashicorm dnf repo
  command:
    cmd: dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
    warn: false
  args:
    creates: /etc/yum.repos.d/hashicorp.repo
  become: yes
  when: ansible_os_family == "RedHat"
