---
- name: Install the latest version of bash
  ansible.builtin.package:
    name: bash
    state: present
  become: "{{ become_for_package }}"

- name: Store the brew prefix
  ansible.builtin.shell:
  cmd: >
    . {{ bash_config }} &&
    brew --prefix
  register: brew_prefix_command
  changed_when: false

- name: Set the default shell to bash
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: "{{ brew_prefix_command.stdout }}/bin/bash"
