---
- name: Include tasks from {{ os }}.yml
  include_tasks: "{{ os }}.yml"

- name: Ensure ~/.bashrc.d
  file:
    path: ~/.bashrc.d
    state: directory

- name: Copy ~/.bashrc.d/50-history.sh
  copy:
    src: .bashrc.d/50-history.sh
    dest: ~/.bashrc.d/50-history.sh
