---
- name: Include variables based on distribution
  include_vars:
    file: "{{ os }}.yml"

- name: Ensure ~/.local/src
  file:
    path: ~/.local/src
    state: directory

- name: Download and extract google-cloud-sdk
  unarchive:
    src: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/{{ google_cloud_sdk_filename }}
    dest: ~/.local/src
    remote_src: yes
