---
- name: Included distribution-specific tasks
  include_tasks: "{{ os }}.yml"

- name: Run ~/.local/src/google-cloud-sdk/install.sh
  command:
    cmd: |
      ~/.local/src/google-cloud-sdk/install.sh
        --usage-reporting false
        --screen-reader false
        --rc-path ~/.bashrc.d/50-google-cloud-sdk.sh
        --command-completion true
        --path-update true
        --additional-components kubectl
        --quiet
    creates: ~/.bashrc.d/50-google-cloud-sdk.sh

- name: Copy ~/.bigqueryrc
  copy:
    src: .bigqueryrc
    dest: ~/.bigqueryrc
