---
- name: Included distribution-specific tasks
  ansible.builtin.include_tasks: "{{ os }}.yml"

- name: Run ~/.local/src/google-cloud-sdk/install.sh
  ansible.builtin.command:
    cmd: |
      ~/.local/src/google-cloud-sdk/install.sh
        --usage-reporting false
        --screen-reader false
        --rc-path ~/.bashrc.d/50-google-cloud-sdk.sh
        --command-completion true
        --path-update true
        --additional-components kubectl
        --quiet
    creates: ~/.bashrc.d/50-google-cloud-sdk.sh

- name: Copy ~/.bigqueryrc
  ansible.builtin.copy:
    src: .bigqueryrc
    dest: ~/.bigqueryrc
    mode: '0644'

- name: export GOOGLE_API_KEY
  ansible.builtin.copy:
    dest: ~/.bashrc.d/50-google-api-key.sh
    content: |
      export GOOGLE_API_KEY={{ google_api_key }}
    mode: '0644'
