---
# Are we in Linux or MacOS?
os: "{{ (ansible_os_family == 'Darwin') | ternary('macos', 'linux') }}"

# When using the `package` module, we need to be sudo on linuxes but the regeular user on macos
# This evaluates to a boolean that can be used like:
#    become: "{{ become_for_package }}"
# when using the package module
become_for_package: "{{ os == 'linux' }}"

# Evaluates to `~/.bashrc` for linuxes, to `~/bash_profile` otherwise.
bash_config: "{{ (os == 'linux') | ternary('~/.bashrc', '~/.bash_profile') }}"

# Base directory where the repo is cloned to
ansible_workstation_path: ~/.local/src/ansible-workstation

# Software Versions

# https://github.com/displaylink-rpm/displaylink-rpm/releases
# https://github.com/displaylink-rpm/displaylink-rpm/releases/download/v5.6.1-1/fedora-37-displaylink-1.12.0-2.x86_64.rpm
displaylink_version: 5.6.1-1
evdi_version: 1.12.0
displaylink_package_version: 2

# Used by DisplayLink role to get path of download
fedora_version: 37

# https://www.gimp.org/downloads/
gimp_major_version: 2.10
gimp_version: 2.10.38

# https://cloud.google.com/sdk/docs/install-sdk
google_cloud_sdk_version: 483.0.0

# https://github.com/gphotosuploader/gphotos-uploader-cli/releases
gphotos_uploader_cli_version: 4.5.0

# https://www.python.org/downloads/
python_versions:
  - 3.13.1
  - 3.12.8
  - 3.11.11
  - 3.10.16

# https://slack.com/downloads/instructions/fedora  (click the "Try Again")
slack_version: 4.32.122
slack_rpm_version: 0.1
slack_distribution: el8

# https://github.com/GoogleCloudPlatform/terraformer/releases
terraformer_version: 0.8.24

# https://github.com/sachaos/viddy/releases
viddy_version: 0.4.0
