---
- name: Ensure ~/.ssh
  ansible.builtin.file:
    path: ~/.ssh
    state: directory
    mode: "700"

- name: Generate SSH key pair
  ansible.builtin.openssh_keypair:
    path: ~/.ssh/id_ed25519
    type: ed25519
    state: present
  register: ssh

- block:
    - name: Add public key to gitlab
      ansible.builtin.shell: GITLAB_HOST=https://gitlab.com glab ssh-key add --title "$(date)" <<< "{{ ssh.public_key }}"
    - name: Add public key to gitlab
      ansible.builtin.shell: GITLAB_HOST={{ gitlab_host }} glab ssh-key add --title "$(date)" <<< "{{ ssh.public_key }}"

    - name: Add public key to github
      ansible.builtin.shell: gh ssh-key add --title "$(date)" <<< "{{ ssh.public_key }}"
  when: ssh is changed
  delegate_to: 127.0.0.1
