---
- block:
  - name: Install zoom rpm key
    rpm_key:
      key: https://us02web.zoom.us/linux/download/pubkey
      state: present

  - name: Install zoom package
    package:
      name: https://us02web.zoom.us/client/latest/zoom_x86_64.rpm
      state: present
  become: "{{ become_for_package }}"
  when: os == "linux"
