---
- name: pip install keyrings.google-artifactregistry-auth
  ansible.builtin.pip:
    name: keyrings.google-artifactregistry-auth
    extra_args: '--index-url https://pypi.org/simple'
    state: present
