---
- name: Run curl https://pyenv.run | bash
  shell:
    cmd: curl https://pyenv.run | bash
    creates: ~/.pyenv

- name: Install Python build dependencies
  ansible.builtin.command: dnf builddep -y python3
  register: dnf_result
  become: yes
  changed_when: '"Nothing to do" not in dnf_result.stdout'
